[package]
name = "aether-edgecloud"
version = "0.1.0"
edition = "2021"

[dependencies]
smoltcp = { version = "0.11", default-features = false, features = ["proto-ipv4", "socket-tcp", "medium-ethernet"] }

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"